# Generated by Django 5.0 on 2024-02-21 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='org',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='user',
        ),
        migrations.RemoveField(
            model_name='yonalish',
            name='faculty',
        ),
        migrations.RemoveField(
            model_name='guruh',
            name='kurs',
        ),
        migrations.RemoveField(
            model_name='guruh',
            name='org',
        ),
        migrations.RemoveField(
            model_name='guruh',
            name='yonalish',
        ),
        migrations.RemoveField(
            model_name='shartnoma',
            name='guruh',
        ),
        migrations.RemoveField(
            model_name='kurs',
            name='org',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='yonalish',
            name='org',
        ),
        migrations.DeleteModel(
            name='Budjet',
        ),
        migrations.DeleteModel(
            name='Faculty',
        ),
        migrations.DeleteModel(
            name='Guruh',
        ),
        migrations.DeleteModel(
            name='Shartnoma',
        ),
        migrations.DeleteModel(
            name='Kurs',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
        migrations.DeleteModel(
            name='Yonalish',
        ),
    ]
