# Generated by Django 5.0 on 2024-03-04 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_budjet_guruhi_alter_shartnoma_guruh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guruh',
            name='bosqich',
            field=models.CharField(choices=[('Bakalavr', 'Bakalavr'), ('Magistr', 'Magistr'), ('Doktorantura', 'Doktorantura')], default='Bakalavr', max_length=100),
        ),
    ]
