# Generated by Django 5.0 on 2024-02-21 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guardian', '0002_generic_permissions_index'),
        ('user', '0005_alter_userrulser_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userrulser',
            name='user',
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.organization')),
                ('rule', models.ManyToManyField(blank=True, to='guardian.userobjectpermission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.userrulser')),
            ],
            options={
                'verbose_name_plural': 'User Models',
            },
        ),
    ]
